FROM node:18.12.1-alpine

WORKDIR /CLIENT_APP_SOURCE

RUN apk add --no-cache autoconf automake file g++ libtool make nasm libpng-dev

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "run", "development"]
