version: "3.8"
services:
    db:
        build:
            context: ./db
            dockerfile: ./Dockerfile
        ports:
            - "27017:27017"
        container_name: "MONGO_CONTAINER"
        volumes:
            - DB_VOLUME:/data/db
        networks:
            - NETWORK
        env_file:
            - ./db/config/.env
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - "5001:5001"
        container_name: "SERVER_CONTAINER"
        volumes:
            - ./server:/SERVER_APP
            - /SERVER_APP/node_modules
        networks:
            - NETWORK
        environment:
            NODE_ENV: development
        env_file:
            - ./db/config/.env
        depends_on:
            - db
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile.development
        ports:
            - "4200:4200"
        container_name: "CLIENT_CONTAINER"
        networks:
            - NETWORK
        volumes:
            - ./client/src:/CLIENT_APP/src
            - /CLIENT_APP/node_modules
volumes:
    DB_VOLUME:
        name: DB_VOLUME
        labels:
            - DB_VOLUME_LABEL
networks:
    NETWORK:
        name: NETWORK
