version: "3.8"
services:
    db:
        build:
            context: ./db
            dockerfile: ./Dockerfile
        container_name: "ERANKETA_MONGO_CONTAINER"
        volumes:
            - DB_VOLUME:/data/db
        networks:
            - NETWORK
        env_file:
            - ./db/config/.env
        restart: unless-stopped
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        container_name: "ERANKETA_SERVER_CONTAINER"
        networks:
            - NETWORK
        environment:
            NODE_ENV: production
        env_file:
            - ./db/config/.env
        depends_on:
            - db
        restart: unless-stopped
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile.production
        container_name: "ERANKETA_CLIENT_CONTAINER"
        networks:
            - NETWORK
        depends_on:
            -   server
        restart: unless-stopped
volumes:
    DB_VOLUME:
        name: DB_VOLUME
        labels:
            - DB_VOLUME_LABEL
networks:
    NETWORK:
        name: NETWORK
